CREATE DATABASE PELUQUERIA_CANINA;
USE PELUQUERIA_CANINA ;

/* TABLA DUENO */

CREATE TABLE DUENO (
DNI_D int,
NOMBRE_D varchar(40),
APELLIDO_D varchar(40),
TELEF_D bigint,
DIRECCION_D varchar (300),
Constraint PK_DNI PRIMARY KEY (DNI_D)
);

/*# TABLA PERRO;*/

CREATE TABLE  PERRO(
ID_PERRO int,
NOMBRE_P varchar(40),
FECHA_NAC date,
SEX_P varchar(40),
DNI_D int,
Constraint PK_IP PRIMARY KEY (ID_PERRO),
Constraint FK_FDD FOREIGN KEY (DNI_D) REFERENCES DUENO (DNI_D)
);				

/*TABLA HISTORIAL */

CREATE TABLE  HISTORIAL(
ID_HIS int,
FECHA_HIS datetime,
PER_HIS int,
DES_HIS varchar(250),
MON_HIS float,
Constraint PK_IP PRIMARY KEY (ID_HIS),
Constraint FK_FPERRO FOREIGN KEY (PER_HIS) REFERENCES PERRO (ID_PERRO)
);


/*#Inserte en la tabla correspondiente un nuevo animal (perro) como paciente y el dueño asociado a ese animal.#;*/


INSERT INTO DUENO VALUES (25247353,"CONSTANTINO","DEBAT",351638499,"MARIANO LARRA 2828");
INSERT INTO PERRO VALUES (1,"CAROLO",'2020-05-16',"MACHO",25247353);
INSERT INTO HISTORIAL VALUES (1,'2020-08-05',1,"CORTE DE PELO",3000);
UPDATE DUENO SET NOMBRE_D ="CONSTANTINO"  WHERE DNI_D=25247353 ;

INSERT INTO DUENO VALUES (30333444,"JUSTINO","NOVARINO",35148022,"PIAMONTE 1000");
INSERT INTO PERRO VALUES (2,"MORENA",'2021-09-22',"EMBRA",30333444);
INSERT INTO HISTORIAL VALUES (2,'2022-05-04',1,"VACUNAS",5000);
UPDATE DUENO SET NOMBRE_D ="JUSTINO"  WHERE DNI_D=30333444;

INSERT INTO DUENO VALUES (50222777,"MARTINO","QUIROGA",3514812077,"CARCANO 1005");
INSERT INTO PERRO VALUES (3,"SIMON",'2017-02-19',"MACHO",50222777);
INSERT INTO HISTORIAL VALUES (3,'2022-01-09',1,"BAÑO Y SECADO",2500);
UPDATE DUENO SET NOMBRE_D ="MARTINO"  WHERE DNI_D=50222777;
UPDATE PERRO SET FECHA_NAC ="2017-02-19"  WHERE DNI_D=50222777;

SHOW DATABASES ;
/*11 Obtener todos los dueños que tengan perros de menos de 5 años de edad */
 /* que no hayan visitado la peluquería en el año 2022. */

SELECT * FROM DUENO ;
SELECT * FROM PERRO;
SELECT * FROM HISTORIAL ;


SELECT NOMBRE_P, SEX_P, FECHA_HIS, DES_HIS, MON_HIS, NOMBRE_D, APELLIDO_D, TIMESTAMPDIFF(YEAR,FECHA_NAC,CURDATE()) AS edad FROM HISTORIAL
INNER JOIN PERRO ON PERRO.ID_PERRO = HISTORIAL.PER_HIS   
INNER JOIN DUENO ON  PERRO.DNI_D=DUENO.DNI_D WHERE (FECHA_HIS > '2022-01-01' and FECHA_HIS < '2022-12-31' ) and TIMESTAMPDIFF(YEAR,FECHA_NAC,CURDATE())< 5 ;

 



